apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-application
spec:
  selector:
    matchLabels:
      app: st2dce-application
  template:
    metadata:
      labels:
        app: st2dce-application
    spec:
      containers:
        - name: st2dce-application
          image: danny07/app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: st2dce-application
spec:
  selector:
    app: st2dce-application
  ports:
    - port: 8080
      targetPort: 8080