apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: st2dce-application
  template:
    metadata:
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: st2dce-application
    spec:
      containers:
        - name: st2dce-application
          image: danny07/app:1.0.31
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: st2dce-application
spec:
  type: LoadBalancer
  selector:
    app: st2dce-application
  ports:
    - port: 8080
      targetPort: 8080
