alertmanager:
  config:
    route:
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'to@email.com'
            from: 'your_email@email.com'
            smarthost: 'smtp.office365.com:587'
            auth_username: 'your_email@email.com'
            auth_password_file: '/etc/alertmanager/secrets/auth_password'
            auth_identity: 'your_email@email.com'
            headers:
              subject: 'ADXA (Antoine, Daniel, Xing, Aliaa): at least 2 replicas in production - Prometheus alert'
  extraVolumeMounts:
    - name: alertmanager-smtp-secret
      mountPath: '/etc/alertmanager/secrets'
      readOnly: true
  extraVolumes:
    - name: alertmanager-smtp-secret
      secret:
        # Kubernetes secret name
        secretName: alertmanager-smtp-secret

serverFiles:
  alerting_rules.yml:
    groups:
      - name: 'Kubernetes at least 2 replicas in production'
        rules:
          - alert: AtLeastTwoReplicasInProduction
            expr: kube_deployment_status_replicas_ready{namespace="production"} < 2
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: Kubernetes At least 2 replicas in production (instance {{ $labels.instance }})
              description: 'Kubernetes At least 2 replicas in production (instance {{ $labels.instance }})'
