apiVersion: 1

datasources:
  datasources.yml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://host.docker.internal:9090
        isDefault: true
        version: 1
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local
        version: 1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        # <int> how often Grafana will scan for changed dashboards
        updateIntervalSeconds: 30
        options:
          # `path` must be /var/lib/grafana/dashboards/<provider_name>
          path: /var/lib/grafana/dashboards/default
          # <bool> use folder names from filesystem to create folders in Grafana
          foldersFromFilesStructure: true
